#!/usr/bin/env bash
# script to transfer file from client to server
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

filename="$1"
ip="$2"
username="$3"
private_key="$4"
destination_path="~/"

options="-o StrictHostKeyChecking=no -i $private_key"

scp $options "$filename" "$username@$ip:$destination_path"

