#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx

# Replace with your server IP or domain
server_name="54.157.134.127"

# Create an Nginx server block configuration file
config_file="/etc/nginx/sites-available/hello-world"
cat <<EOL > $config_file
server {
    listen 80;
    server_name $server_name;
    location / {
        return 200 "Hello World!\n";
    }
}
EOL

# Create a symbolic link to enable the configuration
sudo ln -s $config_file "/etc/nginx/sites-enabled/"

# Test the Nginx configuration
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo service nginx reload

echo "Configuration complete. You can now access 'Hello World!' by running:"
echo "curl http://$server_name/"
