#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# on the 9th iteration print hi
i=0
while ((i < 10))
do
	if [ $i -eq 8 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done       
