#!/usr/bin/env bash
# changing nginx user from root to nginx

# set a user in the config by replace '#user' and it's value
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# now start the nginx service with the new nginx user
sudo -u nginx service nginx start
